### ISSUE TITLE
Add Website to customized profile

### ISSUE THREAD

**Issue by rukundob451** [ArunTeltia/ArunTeltia#2]
-Adding website link to customized profile.

**Comment by ArunTeltia** [comment]
I will add thank you for suggestion @rukundob451

**Comment by ArunTeltia** [comment]
FIxed the issue thank you @rukundob451

**Comment by rukundob451** [comment]
I am glad you did @ArunTeltia, I will be really glad for a follow back, thank you.

**Comment by rukundob451** [comment]
Also a star too if you can, thank you.

**Comment by rukundob451** [comment]
Also a star too if you can, thank you.
